# Generated by Django 5.1.2 on 2025-01-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=25)),
                ('dob', models.DateField(max_length=20)),
                ('cell', models.IntegerField(max_length=20)),
            ],
        ),
    ]
